#A service account provides an identity for processes that run in a Pod.
#RBAC authorization uses the rbac.authorization.k8s.io API group to drive authorization decisions, allowing me to dynamically configure policies through the Kubernetes API.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: safer-gambling-app-prometheus
rules:
- apiGroups: [""]
  resources: ["pods","endpoints","services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safer-gambling-app-prometheusRoleBinding
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: cs-promos-monitoring
roleRef:
  kind: Role
  name: safer-gambling-app-prometheus
  apiGroup: rbac.authorization.k8s.io
